CREATE TABLE BoxScoreDefensiveV2 (
  [gameId] NVARCHAR(MAX),
  [teamId] BIGINT,
  [teamCity] NVARCHAR(MAX),
  [teamName] NVARCHAR(MAX),
  [teamTricode] NVARCHAR(MAX),
  [teamSlug] NVARCHAR(MAX),
  [personId] BIGINT,
  [firstName] NVARCHAR(MAX),
  [familyName] NVARCHAR(MAX),
  [nameI] NVARCHAR(MAX),
  [playerSlug] NVARCHAR(MAX),
  [position] NVARCHAR(MAX),
  [comment] NVARCHAR(MAX),
  [jerseyNum] NVARCHAR(MAX),
  [matchupMinutes] FLOAT,
  [partialPossessions] FLOAT,
  [switchesOn] BIGINT,
  [playerPoints] BIGINT,
  [defensiveRebounds] BIGINT,
  [matchupAssists] BIGINT,
  [matchupTurnovers] BIGINT,
  [steals] BIGINT,
  [blocks] BIGINT,
  [matchupFieldGoalsMade] BIGINT,
  [matchupFieldGoalsAttempted] BIGINT,
  [matchupFieldGoalPercentage] FLOAT,
  [matchupThreePointersMade] BIGINT,
  [matchupThreePointersAttempted] BIGINT,
  [matchupThreePointerPercentage] FLOAT
);

CREATE TABLE playerShootingByShotZoneArea (
  [GAME_ID] BIGINT,
  [PLAYER_ID] BIGINT,
  [POSITION] NVARCHAR(MAX),
  [TEAM_ABBREVIATION] NVARCHAR(MAX),
  [oppAbrv] NVARCHAR(MAX),
  [GAME_DATE] DATETIME,
  [yearSeason] NVARCHAR(MAX),
  [Player_Right_Side_Shot_PCT] FLOAT,
  [Player_Left_Side_Shot_PCT] FLOAT,
  [Player_Left_Center_Shot_PCT] FLOAT,
  [Player_Center_Shot_PCT] FLOAT,
  [Player_Back_Court_Shot_PCT] FLOAT,
  [Player_Right_Center_Shot_PCT] FLOAT,
  [Player_Right_Side_Shot_COUNT] FLOAT,
  [Player_Left_Side_Shot_COUNT] FLOAT,
  [Player_Left_Center_Shot_COUNT] FLOAT,
  [Player_Center_Shot_COUNT] FLOAT,
  [Player_Back_Court_Shot_COUNT] FLOAT,
  [Player_Right_Center_Shot_COUNT] FLOAT
);

CREATE TABLE teamShootingAllowedByShotZoneArea (
  [GAME_ID] BIGINT,
  [TEAM_ID] BIGINT,
  [POSITION] NVARCHAR(MAX),
  [TEAM_ABBREVIATION] NVARCHAR(MAX),
  [oppAbrv] NVARCHAR(MAX),
  [GAME_DATE] DATETIME,
  [yearSeason] NVARCHAR(MAX),
  [Team_Allowed_Right_Side_Shot_PCT] FLOAT,
  [Team_Allowed_Left_Side_Shot_PCT] FLOAT,
  [Team_Allowed_Left_Center_Shot_PCT] FLOAT,
  [Team_Allowed_Center_Shot_PCT] FLOAT,
  [Team_Allowed_Back_Court_Shot_PCT] FLOAT,
  [Team_Allowed_Right_Center_Shot_PCT] FLOAT,
  [Team_Allowed_Right_Side_Shot_COUNT] FLOAT,
  [Team_Allowed_Left_Side_Shot_COUNT] FLOAT,
  [Team_Allowed_Left_Center_Shot_COUNT] FLOAT,
  [Team_Allowed_Center_Shot_COUNT] FLOAT,
  [Team_Allowed_Back_Court_Shot_COUNT] FLOAT,
  [Team_Allowed_Right_Center_Shot_COUNT] FLOAT
);


CREATE TABLE NBACoachs (
  [TEAM_ID] NVARCHAR(MAX),
  [SEASON] NVARCHAR(MAX),
  [COACH_ID] NVARCHAR(MAX),
  [FIRST_NAME] NVARCHAR(MAX),
  [LAST_NAME] NVARCHAR(MAX),
  [COACH_NAME] NVARCHAR(MAX),
  [IS_ASSISTANT] NVARCHAR(MAX),
  [COACH_TYPE] NVARCHAR(MAX),
  [SORT_SEQUENCE] NVARCHAR(MAX),
  [SUB_SORT_SEQUENCE] INT
);

CREATE TABLE CommonTeamRoster (
  [TeamID] NVARCHAR(MAX),
  [SEASON] NVARCHAR(MAX),
  [LeagueID] NVARCHAR(MAX),
  [PLAYER] NVARCHAR(MAX),
  [NICKNAME] NVARCHAR(MAX),
  [PLAYER_SLUG] NVARCHAR(MAX),
  [NUM] NVARCHAR(MAX),
  [POSITION] NVARCHAR(MAX),
  [HEIGHT] NVARCHAR(MAX),
  [WEIGHT] NVARCHAR(MAX),
  [BIRTH_DATE] NVARCHAR(MAX),
  [AGE] FLOAT,
  [EXP] NVARCHAR(MAX),
  [SCHOOL] NVARCHAR(MAX),
  [PLAYER_ID] NVARCHAR(MAX),
  [HOW_ACQUIRED] NVARCHAR(MAX)
);


CREATE TABLE BoxScoreAdvancedV3 (
  [teamId] BIGINT,
  [teamName] NVARCHAR(MAX), 
  [personId] BIGINT,
  [firstName] NVARCHAR(MAX),
  [familyName] NVARCHAR(MAX),
  [position] NVARCHAR(MAX),
  [teamType] NVARCHAR(MAX),
  [minutes] NVARCHAR(MAX),
  [estimatedOffensiveRating] FLOAT,
  [offensiveRating] FLOAT,
  [estimatedDefensiveRating] FLOAT,
  [defensiveRating] FLOAT,
  [estimatedNetRating] FLOAT,
  [netRating] FLOAT,
  [assistPercentage] FLOAT,
  [assistToTurnover] FLOAT,
  [assistRatio] FLOAT,
  [offensiveReboundPercentage] FLOAT,
  [defensiveReboundPercentage] FLOAT,
  [reboundPercentage] FLOAT,
  [turnoverRatio] FLOAT,
  [effectiveFieldGoalPercentage] FLOAT,
  [trueShootingPercentage] FLOAT,
  [usagePercentage] FLOAT,
  [estimatedUsagePercentage] FLOAT,
  [estimatedPace] FLOAT,
  [pace] FLOAT,
  [pacePer40] FLOAT,
  [possessions] FLOAT,
  [PIE] FLOAT
);
