create or alter view current_all_team_stats_for_preds as
with base as (
SELECT lgl.[SEASON_ID]
      ,lgl.[TEAM_ID]
      ,lgl.[TEAM_ABBREVIATION]
	  ,lgl.[oppAbrv]
      ,lgl.[TEAM_NAME]
      ,lgl.[GAME_ID]
      ,lgl.[GAME_DATE]

	  ,ROUND(AVG(CAST(tbsa.offensiveRating AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) TeamORatingLast2
	  ,ROUND(AVG(CAST(tbsa.offensiveRating AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) TeamORatingLast10
	  ,ROUND(AVG(CAST(tbsa.offensiveRating AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) TeamORatingSeason


	  ,ROUND(AVG(CAST(tbsa.defensiveRating AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) TeamDRatingLast2
	  ,ROUND(AVG(CAST(tbsa.defensiveRating AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) TeamDRatingLast10
	  ,ROUND(AVG(CAST(tbsa.defensiveRating AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) TeamDRatingSeason

	  ,ROUND(AVG(CAST(tbsa.netRating AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) TeamNetRatingLast2
	  ,ROUND(AVG(CAST(tbsa.netRating AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) TeamNetRatingLast10
	  ,ROUND(AVG(CAST(tbsa.netRating AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) TeamNetRatingSeason

	  ,ROUND(AVG(CAST(tbsa.PIE AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) TeamPIELast2
	  ,ROUND(AVG(CAST(tbsa.PIE AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) TeamPIELast10
	  ,ROUND(AVG(CAST(tbsa.PIE AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) TeamPIESeason


	  ,ROUND(AVG(CAST(opp_lgl.PTS AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) avgPtsAllowedPerGameLast2
	  ,ROUND(AVG(CAST(opp_lgl.PTS AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) avgPtsAllowedPerGameLast10
	  ,ROUND(AVG(CAST(opp_lgl.PTS AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) avgPtsAllowedPerGameSeason

	  ,ROUND(SUM(CAST(opp_lgl.FGM AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW)
	  /NULLIF(SUM(CAST(opp_lgl.FGA AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),0),2) as FieldGoalPctAllowedLast2
	  ,ROUND(SUM(CAST(opp_lgl.FGM AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW)
	  /NULLIF(SUM(CAST(opp_lgl.FGA AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),0),2) as FieldGoalPctAllowedLast10
	  ,ROUND(SUM(CAST(opp_lgl.FGM AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW)
	  /NULLIF(SUM(CAST(opp_lgl.FGA AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),0),2) as FieldGoalPctAllowedSeason

	  ,ROUND(SUM(CAST(opp_lgl.FG3M AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW)
	  /NULLIF(SUM(CAST(opp_lgl.FG3A AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),0),2) as FieldGoal3PctAllowedLast2
	  ,ROUND(SUM(CAST(opp_lgl.FG3M AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW)
	  /NULLIF(SUM(CAST(opp_lgl.FG3A AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),0),2) as FieldGoal3PctAllowedLast10
	  ,ROUND(SUM(CAST(opp_lgl.FG3M AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW)
	  /NULLIF(SUM(CAST(opp_lgl.FG3A AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),0),2) as FieldGoal3PctAllowedSeason

	  ,ROUND(SUM(CAST(opp_lgl.FTM AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW)
	  /NULLIF(SUM(CAST(opp_lgl.FTA AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),0),2) as FreeThrowPctAllowedLast2
	  ,ROUND(SUM(CAST(opp_lgl.FTM AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW)
	  /NULLIF(SUM(CAST(opp_lgl.FTA AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),0),2) as FreeThrowPctAllowedLast10
	  ,ROUND(SUM(CAST(opp_lgl.FTM AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW)
	  /NULLIF(SUM(CAST(opp_lgl.FTA AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),0),2) as FreeThrowPctAllowedSeason
	  
	  ,ROUND(AVG(CAST(opp_lgl.REB AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) RebsAllowedLast2
	  ,ROUND(AVG(CAST(opp_lgl.REB AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) RebsAllowedLast10
	  ,ROUND(AVG(CAST(opp_lgl.REB AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) RebsAllowedSeason

	  ,ROUND(AVG(CAST(opp_lgl.OREB AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) ORebsAllowedLast2
	  ,ROUND(AVG(CAST(opp_lgl.OREB AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) ORebsAllowedLast10
	  ,ROUND(AVG(CAST(opp_lgl.OREB AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) ORebsAllowedSeason

	  ,ROUND(AVG(CAST(opp_lgl.DREB AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) DRebsAllowedLast2
	  ,ROUND(AVG(CAST(opp_lgl.DREB AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) DRebsAllowedLast10
	  ,ROUND(AVG(CAST(opp_lgl.DREB AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) DRebsAllowedSeason

      ,ROUND(AVG(CAST(opp_lgl.AST AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) AstAllowedLast2
	  ,ROUND(AVG(CAST(opp_lgl.AST AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) AstAllowedLast10
	  ,ROUND(AVG(CAST(opp_lgl.AST AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) AstAllowedSeason

	  ,ROUND(AVG(CAST(opp_lgl.STL AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) StlAllowedLast2
	  ,ROUND(AVG(CAST(opp_lgl.STL AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) StlAllowedLast10
	  ,ROUND(AVG(CAST(opp_lgl.STL AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) StlAllowedSeason

	  ,ROUND(AVG(CAST(opp_lgl.BLK AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) BlkAllowedLast2
	  ,ROUND(AVG(CAST(opp_lgl.BLK AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) BlkAllowedLast10
	  ,ROUND(AVG(CAST(opp_lgl.BLK AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) BlkAllowedSeason

	  ,ROUND(AVG(CAST(opp_lgl.TOV AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) TovAllowedLast2
	  ,ROUND(AVG(CAST(opp_lgl.TOV AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) TovAllowedLast10
	  ,ROUND(AVG(CAST(opp_lgl.TOV AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) TovAllowedSeason

	  ,ROUND(AVG(CAST(opp_tbsa.offensiveRating AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) ORatingAllowedLast2
	  ,ROUND(AVG(CAST(opp_tbsa.offensiveRating AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) ORatingAllowedLast10
	  ,ROUND(AVG(CAST(opp_tbsa.offensiveRating AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) ORatingAllowedSeason


	  ,ROUND(AVG(CAST(opp_tbsa.defensiveRating AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) DRatingAllowedLast2
	  ,ROUND(AVG(CAST(opp_tbsa.defensiveRating AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) DRatingAllowedLast10
	  ,ROUND(AVG(CAST(opp_tbsa.defensiveRating AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) DRatingAllowedSeason

	  ,ROUND(AVG(CAST(opp_tbsa.netRating AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) NetRatingAllowedLast2
	  ,ROUND(AVG(CAST(opp_tbsa.netRating AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) NetRatingAllowedLast10
	  ,ROUND(AVG(CAST(opp_tbsa.netRating AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) NetRatingAllowedSeason

	  ,ROUND(AVG(CAST(opp_tbsa.assistPercentage AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) AstPctAllowedLast2
	  ,ROUND(AVG(CAST(opp_tbsa.assistPercentage AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) AstPctAllowedLast10
	  ,ROUND(AVG(CAST(opp_tbsa.assistPercentage AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) AstPctAllowedSeason

	  ,ROUND(AVG(CAST(opp_tbsa.assistToTurnover AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) AstToTovAllowedLast2
	  ,ROUND(AVG(CAST(opp_tbsa.assistToTurnover AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) AstToTovAllowedLast10
	  ,ROUND(AVG(CAST(opp_tbsa.assistToTurnover AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) AstToTovAllowedSeason

	  ,ROUND(AVG(CAST(opp_tbsa.assistRatio AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) AstRatioAllowedLast2
	  ,ROUND(AVG(CAST(opp_tbsa.assistRatio AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) AstRatioAllowedLast10
	  ,ROUND(AVG(CAST(opp_tbsa.assistRatio AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) AstRatioAllowedSeason

	  ,ROUND(AVG(CAST(opp_tbsa.offensiveReboundPercentage AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) ORebPctAllowedLast2
	  ,ROUND(AVG(CAST(opp_tbsa.offensiveReboundPercentage AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) ORebPctAllowedLast10
	  ,ROUND(AVG(CAST(opp_tbsa.offensiveReboundPercentage AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) ORebPctAllowedSeason

	  ,ROUND(AVG(CAST(opp_tbsa.defensiveReboundPercentage AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) DRebPctAllowedLast2
	  ,ROUND(AVG(CAST(opp_tbsa.defensiveReboundPercentage AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) DRebPctAllowedLast10
	  ,ROUND(AVG(CAST(opp_tbsa.defensiveReboundPercentage AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) DRebPctAllowedSeason

	  ,ROUND(AVG(CAST(opp_tbsa.reboundPercentage AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) RebPctAllowedLast2
	  ,ROUND(AVG(CAST(opp_tbsa.reboundPercentage AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) RebPctAllowedLast10
	  ,ROUND(AVG(CAST(opp_tbsa.reboundPercentage AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) RebPctAllowedSeason

	  ,ROUND(AVG(CAST(opp_tbsa.turnoverRatio AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) TovRatioAllowedLast2
	  ,ROUND(AVG(CAST(opp_tbsa.turnoverRatio AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) TovRatioAllowedLast10
	  ,ROUND(AVG(CAST(opp_tbsa.turnoverRatio AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) TovRatioAllowedSeason

	  ,ROUND(AVG(CAST(opp_tbsa.effectiveFieldGoalPercentage AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) EffFldGoalPctAllowedLast2
	  ,ROUND(AVG(CAST(opp_tbsa.effectiveFieldGoalPercentage AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) EffFldGoalPctAllowedLast10
	  ,ROUND(AVG(CAST(opp_tbsa.effectiveFieldGoalPercentage AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) EffFldGoalPctAllowedSeason
      
	  ,ROUND(AVG(CAST(opp_tbsa.trueShootingPercentage AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) TruShoPctAllowedLast2
	  ,ROUND(AVG(CAST(opp_tbsa.trueShootingPercentage AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) TruShoPctPctAllowedLast10
	  ,ROUND(AVG(CAST(opp_tbsa.trueShootingPercentage AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) TruShoPctPctAllowedSeason

	  ,ROUND(AVG(CAST(opp_tbsa.pace AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) PaceAllowedLast2
	  ,ROUND(AVG(CAST(opp_tbsa.pace AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) PaceAllowedLast10
	  ,ROUND(AVG(CAST(opp_tbsa.pace AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) PaceAllowedSeason

	  ,ROUND(AVG(CAST(opp_tbsa.pacePer40 AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) PacePer40AllowedLast2
	  ,ROUND(AVG(CAST(opp_tbsa.pacePer40 AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) PacePer40AllowedLast10
	  ,ROUND(AVG(CAST(opp_tbsa.pacePer40 AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) PacePer40AllowedSeason
	  
	  ,ROUND(AVG(CAST(opp_tbsa.possessions AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) PossessionsAllowedLast2
	  ,ROUND(AVG(CAST(opp_tbsa.possessions AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) PossessionsAllowedLast10
	  ,ROUND(AVG(CAST(opp_tbsa.possessions AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) PossessionsAllowedSeason
      
	  ,ROUND(AVG(CAST(opp_tbsa.PIE AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) PIEAllowedLast2
	  ,ROUND(AVG(CAST(opp_tbsa.PIE AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) PIEAllowedLast10
	  ,ROUND(AVG(CAST(opp_tbsa.PIE AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) PIEAllowedSeason
     
	  ,ROUND(AVG(CAST(opp_tbss.percentageFieldGoalsAttempted2pt AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) FGAPct2AtmtAllowedLast2
	  ,ROUND(AVG(CAST(opp_tbss.percentageFieldGoalsAttempted2pt AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) FGAPct2AtmtAllowedLast10
	  ,ROUND(AVG(CAST(opp_tbss.percentageFieldGoalsAttempted2pt AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) FGAPct2AtmtAllowedSeason

	  ,ROUND(AVG(CAST(opp_tbss.percentageFieldGoalsAttempted3pt AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) FGAPct3AtmtAllowedLast2
	  ,ROUND(AVG(CAST(opp_tbss.percentageFieldGoalsAttempted3pt AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) FGAPct3AtmtAllowedLast10
	  ,ROUND(AVG(CAST(opp_tbss.percentageFieldGoalsAttempted3pt AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) FGAPct3AtmtAllowedSeason

	  ,ROUND(AVG(CAST(opp_tbss.percentagePoints2pt AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) PctPts2PtrsAllowedLast2
	  ,ROUND(AVG(CAST(opp_tbss.percentagePoints2pt AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) PctPts2PtrsAllowedLast10
	  ,ROUND(AVG(CAST(opp_tbss.percentagePoints2pt AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) PctPts2PtrsAllowedSeason
	  
	  ,ROUND(AVG(CAST(opp_tbss.percentagePoints3pt AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) PctPts3PtrsAllowedLast2
	  ,ROUND(AVG(CAST(opp_tbss.percentagePoints3pt AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) PctPts3PtrsAllowedLast10
	  ,ROUND(AVG(CAST(opp_tbss.percentagePoints3pt AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) PctPts3PtrsAllowedSeason

	  ,ROUND(AVG(CAST(opp_tbss.percentagePointsMidrange2pt AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) PctPtsMidRange2PtrsAllowedLast2
	  ,ROUND(AVG(CAST(opp_tbss.percentagePointsMidrange2pt AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) PctPtsMidRange2PtrsAllowedLast10
	  ,ROUND(AVG(CAST(opp_tbss.percentagePointsMidrange2pt AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) PctPtsMidRange2PtrsAllowedSeason

      ,ROUND(AVG(CAST(opp_tbss.percentagePointsFastBreak AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) PctPtsFastBreakPtrsAllowedLast2
	  ,ROUND(AVG(CAST(opp_tbss.percentagePointsFastBreak AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) PctPtsFastBreakPtrsAllowedLast10
	  ,ROUND(AVG(CAST(opp_tbss.percentagePointsFastBreak AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) PctPtsFastBreakPtrsAllowedSeason

	  ,ROUND(AVG(CAST(opp_tbss.percentagePointsFreeThrow AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) PctPtsFreeThrwPtrsAllowedLast2
	  ,ROUND(AVG(CAST(opp_tbss.percentagePointsFreeThrow AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) PctPtsFreeThrwPtrsAllowedLast10
	  ,ROUND(AVG(CAST(opp_tbss.percentagePointsFreeThrow AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) PctPtsFreeThrwPtrsAllowedSeason

	  ,ROUND(AVG(CAST(opp_tbss.percentagePointsOffTurnovers AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) PctPtsOffTovPtrsAllowedLast2
	  ,ROUND(AVG(CAST(opp_tbss.percentagePointsOffTurnovers AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) PctPtsOffTovPtrsAllowedLast10
	  ,ROUND(AVG(CAST(opp_tbss.percentagePointsOffTurnovers AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) PctPtsOffTovPtrsAllowedSeason

	  ,ROUND(AVG(CAST(opp_tbss.percentagePointsPaint AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) PctPtsInPaintAllowedLast2
	  ,ROUND(AVG(CAST(opp_tbss.percentagePointsPaint AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) PctPtsInPaintAllowedLast10
	  ,ROUND(AVG(CAST(opp_tbss.percentagePointsPaint AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) PctPtsInPaintAllowedSeason

	  ,ROUND(AVG(CAST(opp_tbss.percentageAssisted2pt AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) PctPtsAstsed2AllowedLast2
	  ,ROUND(AVG(CAST(opp_tbss.percentageAssisted2pt AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) PctPtsAstsed2AllowedLast10
	  ,ROUND(AVG(CAST(opp_tbss.percentageAssisted2pt AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) PctPtsAstsed2AllowedSeason

	  ,ROUND(AVG(CAST(opp_tbss.percentageUnassisted2pt AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) PctPtsUnAstsed2AllowedLast2
	  ,ROUND(AVG(CAST(opp_tbss.percentageUnassisted2pt AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) PctPtsUnAstsed2AllowedLast10
	  ,ROUND(AVG(CAST(opp_tbss.percentageUnassisted2pt AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) PctPtsUnAstsed2AllowedSeason

	  ,ROUND(AVG(CAST(opp_tbss.percentageAssisted3pt AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) PctPtsAstsed3AllowedLast2
	  ,ROUND(AVG(CAST(opp_tbss.percentageAssisted3pt AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) PctPtsAstsed3AllowedLast10
	  ,ROUND(AVG(CAST(opp_tbss.percentageAssisted3pt AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) PctPtsAstsed3AllowedSeason

	  ,ROUND(AVG(CAST(opp_tbss.percentageUnassisted3pt AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) PctPtsUnAstsed3AllowedLast2
	  ,ROUND(AVG(CAST(opp_tbss.percentageUnassisted3pt AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) PctPtsUnAstsed3AllowedLast10
	  ,ROUND(AVG(CAST(opp_tbss.percentageUnassisted3pt AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) PctPtsUnAstsed3AllowedSeason

	  ,ROUND(AVG(CAST(opp_tbss.percentageAssistedFGM AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) PctPtsAstsedAllowedLast2
	  ,ROUND(AVG(CAST(opp_tbss.percentageAssistedFGM AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) PctPtsAstsedAllowedLast10
	  ,ROUND(AVG(CAST(opp_tbss.percentageAssistedFGM AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) PctPtsAstsedAllowedSeason

	  ,ROUND(AVG(CAST(opp_tbss.percentageUnassistedFGM AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) PctPtsUnAstsedAllowedLast2
	  ,ROUND(AVG(CAST(opp_tbss.percentageUnassistedFGM AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) PctPtsUnAstsedAllowedLast10
	  ,ROUND(AVG(CAST(opp_tbss.percentageUnassistedFGM AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) PctPtsUnAstsedAllowedSeason

	  ,ROUND(AVG(CAST(opp_tbst.distance AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) DistanceAllowedLast2
	  ,ROUND(AVG(CAST(opp_tbst.distance AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) DistanceAllowedLast10
	  ,ROUND(AVG(CAST(opp_tbst.distance AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) DistanceAllowedSeason

	  ,ROUND(AVG(CAST(opp_tbst.reboundChancesOffensive AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) ORebChncsAllowedLast2
	  ,ROUND(AVG(CAST(opp_tbst.reboundChancesOffensive AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) ORebChncsAllowedLast10
	  ,ROUND(AVG(CAST(opp_tbst.reboundChancesOffensive AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) ORebChncsAllowedSeason

	  ,ROUND(AVG(CAST(opp_tbst.reboundChancesDefensive AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) DRebChncsAllowedLast2
	  ,ROUND(AVG(CAST(opp_tbst.reboundChancesDefensive AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) DRebChncsAllowedLast10
	  ,ROUND(AVG(CAST(opp_tbst.reboundChancesDefensive AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) DRebChncsAllowedSeason

	  ,ROUND(AVG(CAST(opp_tbst.reboundChancesTotal AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) RebChncsAllowedLast2
	  ,ROUND(AVG(CAST(opp_tbst.reboundChancesTotal AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) RebChncsAllowedLast10
	  ,ROUND(AVG(CAST(opp_tbst.reboundChancesTotal AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) RebChncsAllowedSeason
	  
	  ,ROUND(AVG(CAST(opp_tbst.touches AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) TchsAllowedLast2
	  ,ROUND(AVG(CAST(opp_tbst.touches AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) TchsAllowedLast10
	  ,ROUND(AVG(CAST(opp_tbst.touches AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) TchsAllowedSeason

	  ,ROUND(AVG(CAST(opp_tbst.secondaryAssists AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) SecdryAstAllowedLast2
	  ,ROUND(AVG(CAST(opp_tbst.secondaryAssists AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) SecdryAstAllowedLast10
	  ,ROUND(AVG(CAST(opp_tbst.secondaryAssists AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) SecdryAstAllowedSeason

	  ,ROUND(AVG(CAST(opp_tbst.freeThrowAssists AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) FTAstAllowedLast2
	  ,ROUND(AVG(CAST(opp_tbst.freeThrowAssists AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) FTAstAllowedLast10
	  ,ROUND(AVG(CAST(opp_tbst.freeThrowAssists AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) FTAstAllowedSeason

	  ,ROUND(AVG(CAST(opp_tbst.passes AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) PassesAllowedLast2
	  ,ROUND(AVG(CAST(opp_tbst.passes AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),2) PassesAllowedLast10
	  ,ROUND(AVG(CAST(opp_tbst.passes AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),2) PassesAllowedSeason

	  ,ROUND(SUM(CAST(opp_tbst.contestedFieldGoalsMade AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW)
	  /NULLIF(SUM(CAST(opp_tbst.contestedFieldGoalsAttempted AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),0),2) as ContestedFieldGoalPctAllowedLast2
	  ,ROUND(SUM(CAST(opp_tbst.contestedFieldGoalsMade AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW)
	  /NULLIF(SUM(CAST(opp_tbst.contestedFieldGoalsAttempted AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),0),2) as ContestedFieldGoalPctAllowedLast10
	  ,ROUND(SUM(CAST(opp_tbst.contestedFieldGoalsMade AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW)
	  /NULLIF(SUM(CAST(opp_tbst.contestedFieldGoalsAttempted AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),0),2) as ContestedFieldGoalPctAllowedSeason

	  ,ROUND(SUM(CAST(opp_tbst.uncontestedFieldGoalsMade AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW)
	  /NULLIF(SUM(CAST(opp_tbst.uncontestedFieldGoalsAttempted AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),0),2) as UnContestedFieldGoalPctAllowedLast2
	  ,ROUND(SUM(CAST(opp_tbst.uncontestedFieldGoalsMade AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW)
	  /NULLIF(SUM(CAST(opp_tbst.uncontestedFieldGoalsAttempted AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),0),2) as UnContestedFieldGoalPctAllowedLast10
	  ,ROUND(SUM(CAST(opp_tbst.uncontestedFieldGoalsMade AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW)
	  /NULLIF(SUM(CAST(opp_tbst.uncontestedFieldGoalsAttempted AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),0),2) as UnContestedFieldGoalPctAllowedSeason

	  ,ROUND(SUM(CAST(opp_tbst.defendedAtRimFieldGoalsMade AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW)
	  /NULLIF(SUM(CAST(opp_tbst.defendedAtRimFieldGoalsAttempted AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),0),2) as DefendedAtRimFieldGoalPctAllowedLast2
	  ,ROUND(SUM(CAST(opp_tbst.defendedAtRimFieldGoalsMade AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW)
	  /NULLIF(SUM(CAST(opp_tbst.defendedAtRimFieldGoalsAttempted AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),0),2) as DefendedAtRimFieldGoalPctAllowedLast10
	  ,ROUND(SUM(CAST(opp_tbst.defendedAtRimFieldGoalsMade AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW)
	  /NULLIF(SUM(CAST(opp_tbst.defendedAtRimFieldGoalsAttempted AS FLOAT)) OVER (PARTITION BY lgl.TEAM_ABBREVIATION, lgl.[yearSeason] ORDER BY lgl.GAME_DATE ROWS BETWEEN 82 PRECEDING AND CURRENT ROW),0),2) as DefendedAtRimFieldGoalPctAllowedSeason
	  , rank() over (partition by lgl.TEAM_ABBREVIATION order by lgl.GAME_DATE desc) as ranking

  FROM [nba_game_data].[dbo].[LeagueGameLog] lgl

  LEFT OUTER JOIN [nba_game_data].[dbo].[TeamBoxScoreAdvancedV3] tbsa
  on
  lgl.TEAM_ID = tbsa.teamId
  and lgl.GAME_ID = tbsa.gameId

  LEFT OUTER JOIN [nba_game_data].[dbo].[LeagueGameLog] opp_lgl
  on
  lgl.oppAbrv = opp_lgl.TEAM_ABBREVIATION
  and lgl.GAME_ID = opp_lgl.GAME_ID

  LEFT OUTER JOIN [nba_game_data].[dbo].[TeamBoxScoreAdvancedV3] opp_tbsa
  on
  opp_lgl.TEAM_ID = opp_tbsa.teamId
  and opp_lgl.GAME_ID = opp_tbsa.gameId

  LEFT OUTER JOIN [nba_game_data].[dbo].[TeamBoxScoreScoringV3] opp_tbss
  on
  opp_lgl.TEAM_ID = opp_tbss.teamId
  and opp_lgl.GAME_ID = opp_tbss.gameId

  LEFT OUTER JOIN [nba_game_data].[dbo].[TeamBoxScorePlayerTrackV3] opp_tbst
  on
  opp_lgl.TEAM_ID = opp_tbst.teamId
  and opp_lgl.GAME_ID = opp_tbst.gameId
  
  
  where lgl.yearSeason >= 2023
  --and lgl.GAME_ID=22300154
  )
  select * 
  from base 
  where 
  ranking = 1