create view action_type as

WITH basic_stats AS (
    SELECT 
        PLAYER_ID,
        PLAYER_NAME,
        GAME_ID,
        [Driving Bank shot],
        [Hook Shot],
        [Driving Jump shot],
        [Running Hook Shot],
        [Tip Layup Shot],
        [Step Back Jump shot],
        [Running Finger Roll Layup Shot],
        [Pullup Bank shot],
        [Driving Reverse Layup Shot],
        [Running Layup Shot],
        [Alley Oop Layup shot],
        [Driving Hook Shot],
        [Alley Oop Dunk Shot],
        [Running Alley Oop Dunk Shot],
        [Turnaround Jump Shot],
        [Reverse Dunk Shot],
        [Running Pull-Up Jump Shot],
        [Driving Layup Shot],
        [Turnaround Fadeaway shot],
        [Driving Floating Jump Shot],
        [Driving Dunk Shot],
        [Cutting Dunk Shot],
        [Running Dunk Shot],
        [Running Reverse Dunk Shot],
        [Running Jump Shot],
        [Driving Reverse Dunk Shot],
        [Putback Layup Shot],
        [Fadeaway Bank shot],
        [Hook Bank Shot],
        [Tip Dunk Shot],
        [Step Back Bank Jump Shot],
        [No Shot],
        [Pullup Jump shot],
        [Turnaround Bank shot],
        [Running Reverse Layup Shot],
        [Turnaround Fadeaway Bank Jump Shot],
        [Running Alley Oop Layup Shot],
        [Finger Roll Layup Shot],
        [Cutting Layup Shot],
        [Turnaround Bank Hook Shot],
        [Floating Jump shot],
        [Layup Shot],
        [Dunk Shot],
        [Turnaround Hook Shot],
        [Reverse Layup Shot],
        [Cutting Finger Roll Layup Shot],
        [Driving Floating Bank Jump Shot],
        [Fadeaway Jump Shot],
        [Jump Bank Shot],
        [Driving Finger Roll Layup Shot],
        [Putback Dunk Shot],
        [Driving Bank Hook Shot],
        [Jump Shot]
    FROM 
        (SELECT 
            [GAME_ID],
            [PLAYER_ID],
            [PLAYER_NAME],
            [ACTION_TYPE],
            AVG(CAST([SHOT_MADE_FLAG] as FLOAT)) as Shot_Pct
        FROM [nba_game_data].[dbo].[ShotChartDetail]
        GROUP BY
            [GAME_ID],
            [PLAYER_ID],
            [PLAYER_NAME],
            [ACTION_TYPE]) AS SourceTable
    PIVOT 
        (
            AVG(Shot_Pct)
            FOR ACTION_TYPE IN (
                [Driving Bank shot],
                [Hook Shot],
                [Driving Jump shot],
                [Running Hook Shot],
                [Tip Layup Shot],
                [Step Back Jump shot],
                [Running Finger Roll Layup Shot],
                [Pullup Bank shot],
                [Driving Reverse Layup Shot],
                [Running Layup Shot],
                [Alley Oop Layup shot],
                [Driving Hook Shot],
                [Alley Oop Dunk Shot],
                [Running Alley Oop Dunk Shot],
                [Turnaround Jump Shot],
                [Reverse Dunk Shot],
                [Running Pull-Up Jump Shot],
                [Driving Layup Shot],
                [Turnaround Fadeaway shot],
                [Driving Floating Jump Shot],
                [Driving Dunk Shot],
                [Cutting Dunk Shot],
                [Running Dunk Shot],
                [Running Reverse Dunk Shot],
                [Running Jump Shot],
                [Driving Reverse Dunk Shot],
                [Putback Layup Shot],
                [Fadeaway Bank shot],
                [Hook Bank Shot],
                [Tip Dunk Shot],
                [Step Back Bank Jump Shot],
                [No Shot],
                [Pullup Jump shot],
                [Turnaround Bank shot],
                [Running Reverse Layup Shot],
                [Turnaround Fadeaway Bank Jump Shot],
                [Running Alley Oop Layup Shot],
                [Finger Roll Layup Shot],
                [Cutting Layup Shot],
                [Turnaround Bank Hook Shot],
                [Floating Jump shot],
                [Layup Shot],
                [Dunk Shot],
                [Turnaround Hook Shot],
                [Reverse Layup Shot],
                [Cutting Finger Roll Layup Shot],
                [Driving Floating Bank Jump Shot],
                [Fadeaway Jump Shot],
                [Jump Bank Shot],
                [Driving Finger Roll Layup Shot],
                [Putback Dunk Shot],
                [Driving Bank Hook Shot],
                [Jump Shot]
            )
        ) AS PivotTable
)
SELECT 
    PLAYER_ID AS PLAYER_ID,
    PLAYER_NAME AS PLAYER_NAME,
    GAME_ID AS GAME_ID,
    COALESCE([Driving Bank shot], 0) AS Driving_Bank_shot,
    COALESCE([Hook Shot], 0) AS Hook_Shot,
    COALESCE([Driving Jump shot], 0) AS Driving_Jump_shot,
        COALESCE([Running Hook Shot], 0) AS Running_Hook_Shot,
    COALESCE([Tip Layup Shot], 0) AS Tip_Layup_Shot,
    COALESCE([Step Back Jump shot], 0) AS Step_Back_Jump_shot,
    COALESCE([Running Finger Roll Layup Shot], 0) AS Running_Finger_Roll_Layup_Shot,
    COALESCE([Pullup Bank shot], 0) AS Pullup_Bank_shot,
    COALESCE([Driving Reverse Layup Shot], 0) AS Driving_Reverse_Layup_Shot,
    COALESCE([Running Layup Shot], 0) AS Running_Layup_Shot,
    COALESCE([Alley Oop Layup shot], 0) AS Alley_Oop_Layup_shot,
    COALESCE([Driving Hook Shot], 0) AS Driving_Hook_Shot,
    COALESCE([Alley Oop Dunk Shot], 0) AS Alley_Oop_Dunk_Shot,
    COALESCE([Running Alley Oop Dunk Shot], 0) AS Running_Alley_Oop_Dunk_Shot,
    COALESCE([Turnaround Jump Shot], 0) AS Turnaround_Jump_Shot,
    COALESCE([Reverse Dunk Shot], 0) AS Reverse_Dunk_Shot,
    COALESCE([Running Pull-Up Jump Shot], 0) AS Running_Pull_Up_Jump_Shot,
    COALESCE([Driving Layup Shot], 0) AS Driving_Layup_Shot,
    COALESCE([Turnaround Fadeaway shot], 0) AS Turnaround_Fadeaway_shot,
    COALESCE([Driving Floating Jump Shot], 0) AS Driving_Floating_Jump_Shot,
    COALESCE([Driving Dunk Shot], 0) AS Driving_Dunk_Shot,
    COALESCE([Cutting Dunk Shot], 0) AS Cutting_Dunk_Shot,
    COALESCE([Running Dunk Shot], 0) AS Running_Dunk_Shot,
    COALESCE([Running Reverse Dunk Shot], 0) AS Running_Reverse_Dunk_Shot,
    COALESCE([Running Jump Shot], 0) AS Running_Jump_Shot,
    COALESCE([Driving Reverse Dunk Shot], 0) AS Driving_Reverse_Dunk_Shot,
    COALESCE([Putback Layup Shot], 0) AS Putback_Layup_Shot,
    COALESCE([Fadeaway Bank shot], 0) AS Fadeaway_Bank_shot,
    COALESCE([Hook Bank Shot], 0) AS Hook_Bank_Shot,
    COALESCE([Tip Dunk Shot], 0) AS Tip_Dunk_Shot,
    COALESCE([Step Back Bank Jump Shot], 0) AS Step_Back_Bank_Jump_Shot,
    COALESCE([No Shot], 0) AS No_Shot,
    COALESCE([Pullup Jump shot], 0) AS Pullup_Jump_shot,
    COALESCE([Turnaround Bank shot], 0) AS Turnaround_Bank_shot,
    COALESCE([Running Reverse Layup Shot], 0) AS Running_Reverse_Layup_Shot,
    COALESCE([Turnaround Fadeaway Bank Jump Shot], 0) AS Turnaround_Fadeaway_Bank_Jump_Shot,
    COALESCE([Running Alley Oop Layup Shot], 0) AS Running_Alley_Oop_Layup_Shot,
    COALESCE([Finger Roll Layup Shot], 0) AS Finger_Roll_Layup_Shot,
    COALESCE([Cutting Layup Shot], 0) AS Cutting_Layup_Shot,
    COALESCE([Turnaround Bank Hook Shot], 0) AS Turnaround_Bank_Hook_Shot,
    COALESCE([Floating Jump shot], 0) AS Floating_Jump_shot,
    COALESCE([Layup Shot], 0) AS Layup_Shot,
    COALESCE([Dunk Shot], 0) AS Dunk_Shot,
    COALESCE([Turnaround Hook Shot], 0) AS Turnaround_Hook_Shot,
    COALESCE([Reverse Layup Shot], 0) AS Reverse_Layup_Shot,
    COALESCE([Cutting Finger Roll Layup Shot], 0) AS Cutting_Finger_Roll_Layup_Shot,
    COALESCE([Driving Floating Bank Jump Shot], 0) AS Driving_Floating_Bank_Jump_Shot,
    COALESCE([Fadeaway Jump Shot], 0) AS Fadeaway_Jump_Shot,
    COALESCE([Jump Bank Shot], 0) AS Jump_Bank_Shot,
    COALESCE([Driving Finger Roll Layup Shot], 0) AS Driving_Finger_Roll_Layup_Shot,
    COALESCE([Putback Dunk Shot], 0) AS Putback_Dunk_Shot,
    COALESCE([Driving Bank Hook Shot], 0) AS Driving_Bank_Hook_Shot,
    COALESCE([Jump Shot], 0) AS Jump_Shot
FROM basic_stats


